# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46a288255ee57870d462e7abeb906e3f33965904847aa724c5f20bb02db15886aa362f0675c0f7528af8912d6e9ec6aeac5c556a9a769dd572f37d57e0f7c09

test:
  secret_key_base: fe903cf43ce7d322c301cd189ce7bcff8a898d6a22f686794f768c4a775b96d33e587c7ec680092511a3282e0b0d09cc73df45a2e429ffa88446e1950bd83743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
